server:
  port: 3375
  address: 0.0.0.0

logging:
  file: /var/log/alert/alert.log
#  config: /usr/local/alert/etc/alert.xml
#  level:
#    org.rest.alert.service.smsSender: Debug

mq:
  address: 10.150.68.133
  port: 60001

app:
  id: ""
  password: ""

bus:
  subject: CSGC2NARIAlertSend

auth:
  name: admin
  password: 123456

address:
  down:
    ip: 127.0.0.1
    port: 8080
  up:
    ip: 127.0.0.1
    port: 8080

